### ISSUE TITLE
 Input_file1 TF format

### ISSUE THREAD

**Issue by sgmccalla** [hmatsu1226/SCODE#1]
For Input_file1, do the transcription factors have to be at the beginning of the G x C matrix? 

So for example, if I put 10 for the G parameter, do the 10 transcription factors have to be in the first 10 rows of the Input_file1 matrix?

**Comment by hmatsu1226** [comment]
Yes, the input file is the G x C matrix, where G and C are the number of TFs and cells, respectively.

**Comment by sgmccalla** [comment]
Thank you very much for following up. 

To clarify, should the Input_file1 **_only_** contain TFs for G then? So, if I have an scRNA-seq dataset that has counts for 10,000 genes and 2,000 cells, but my TF list only has 10 out of the 10,000 genes, should the Input_file1 be a 10 x 2,000 matrix? Or a 10,000 x 2,000 matrix?

**Comment by hmatsu1226** [comment]
Yes, SCODE is designed for TF-TF network inference, and the Input_file must be a 10 x 2,000 matrix.
If you want to infer TF-gene network, I recommend other algorithm (such as GENIE3).
