### ISSUE TITLE
Output interpretation

### ISSUE THREAD

**Issue by MingBit** [hmatsu1226/SCODE#2]
Hallo,

I was testing this package with my own dataset and confused with results. For instance, it says that A.txt contains the relationship between TF_i and TF_j. I found A_ii are positive or negative, so what does this mean with TF_i itself ? 

I'd like to generate a linkage table from the results. But I'm not sure how to do with A.txt?
One more question, whether this is meaningful if I have only one time point dataset?

Thank you in advance and looking forward to your response.

**Comment by hmatsu1226** [comment]
Hi,

The positive and negative values represent up-regulation and
down-regulation, respectively.
The diagonal element (Aii) represents self-regulation, which means positive
or negative feedback.

SCODE uses time information to learn dynamics model and is designed for
dense time-series expression data.
Therefore, SCODE is not effectual for one time point dataset.

If you have any questions or anything, please do not hesitate to contact me.

2019年6月30日(日) 2:07 MingBit <notifications@github.com>:
