### ISSUE TITLE
How to extract GRN at different time point ?

### ISSUE THREAD

**Issue by gaochenxuzi** [hmatsu1226/SCODE#3]
Hello, Thans for your efficient algorithm .
I'd like to know whether I can extract different TF-TF regulatory network at each time point ( such as TF1 - TF2  regulatory coefficient may different at different time ). 
Looking forward to your reply !
Chenxu Gao

**Comment by hmatsu1226** [comment]
Hello.

Unfortunately, SCODE assumes that the regulatory network is constant and cannot be used for the purpose.
I think the following papers might be of help.
https://academic.oup.com/nar/article/47/11/e62/5377474
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007471

**Comment by gaochenxuzi** [comment]
> Hello.
> 
> Unfortunately, SCODE assumes that the regulatory network is constant and cannot be used for the purpose.
> I think the following papers might be of help.
> https://academic.oup.com/nar/article/47/11/e62/5377474
> https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007471

Thanks for your guidance and quick response !
