### ISSUE TITLE
Interpreting the TFTF_reference network in data

### ISSUE THREAD

**Issue by atl1502** [hmatsu1226/SCODE#4]
I am currently playing around with the data used for testing. In the files, there is a TFTF reference file. I am a bit confused about how to interpret the 3rd and 4th columns of the dataset and how it was used to create the correct network. How exactly were those numbers normalized? Thanks!

**Comment by hmatsu1226** [comment]
The 3rd and 4th columns simply show the index of the TF (in tf.txt).
The network is derived from a database based on a different experimental resource, and "The gene in the first column is bound (ie contains a DNaseI footprint in proximal regulatory DNA) corresponding to the second column's TF gene product."
http://www.regulatorynetworks.org

**Comment by atl1502** [comment]
I see, thank you!
