### ISSUE TITLE
Errors when runing SCODE

### ISSUE THREAD

**Issue by chengyuye** [hmatsu1226/SCODE#5]
Hi,

Thanks for developing this tool. I'm using SCODE for GRN analysis along the pseudotime. Specifically, I have 1089 cells and 115 transcriptional factors. I have obtained the input_file 1 (115 x 1089), and input_file 2 (1089 lines). When running SCODE using the following code :

`Rscript SCODE.R TF_matrix.txt pseudotime_point.txt 115 4 1089 50`

I kept getting this error message: 
`Error in 1:maxite : NA/NaN argument
 Execution halt`

But I have checked my files and there is no 'NA' in them. Could you please give me some help? I've attached my input files in case any need. Much appreciated! 
[pseudotime_point.txt](https://github.com/hmatsu1226/SCODE/files/8553194/pseudotime_point.txt)
[TF_pseudotime.txt](https://github.com/hmatsu1226/SCODE/files/8553195/TF_pseudotime.txt)
uch appreciated!

**Comment by hmatsu1226** [comment]
Thank you for your interest in this tool.
Could you please give me "TF_matrix.txt"?

**Comment by chengyuye** [comment]
> Thank you for your interest in this tool. Could you please give me "TF_matrix.txt"?

Thank you very much for your reply! Sorry for the mistake. Here is the 'TF_matrix.txt' file. Cheers!
[TF_matrix.txt](https://github.com/hmatsu1226/SCODE/files/8559043/TF_matrix.txt)

**Comment by hmatsu1226** [comment]
Thanks for the file. I noticed a mistake in the first run command. Could you try the following command?
```
Rscript SCODE.R TF_matrix.txt pseudotime_point.txt output 115 4 1089 50
```
After execution, a directory named "output" is created and the files are output in it.

**Comment by chengyuye** [comment]
> Thanks for the file. I noticed a mistake in the first run command. Could you try the following command?
> 
> ```
> Rscript SCODE.R TF_matrix.txt pseudotime_point.txt output 115 4 1089 50
> ```
> 
> After execution, a directory named "output" is created and the files are output in it.

Successfully done! Please bear with my stupid mistakes and thank you so much for your instructions!
